<a href="https://colab.research.google.com/github/Viratdwvd/AIML_Learning/blob/main/Missing_Attribute.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#To take care of missing attribute ,you have three option:
#Get rid of missing data point
#Get rid of whole attribute
# set the value to some value (0,mean,median)

In [2]:
import pandas as pd
import numpy as np
from sklearn import datasets
housing = pd.read_csv('/content/housing.csv')

In [3]:
housing.info()
housing.keys()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAR     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      501 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

Index(['CRIM', 'ZN', 'INDUS', 'CHAR', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [4]:
housing

,CRIM,ZN,INDUS,CHAR,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.00
1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.01
2,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.02
3,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,NaN,15.3,396.90,4.98,24.03
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.40
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.60
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.90
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.00
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.90

In [5]:
a=housing.dropna(subset=["TAX"])
a.shape

(501, 14)

In [6]:
housing.drop("TAX",axis=1).shape

(506, 13)

In [8]:
median=housing["TAX"].median()
housing["TAX"].fillna(median)

0      296.0
1      296.0
2      296.0
3      330.0
4      222.0
       ...
501    273.0
502    273.0
503    273.0
504    273.0
505    273.0
Name: TAX, Length: 506, dtype: float64

In [15]:
!pip install sklearn.impute==0.24.2
!pip install sklearn.impute

ERROR: Could not find a version that satisfies the requirement sklearn.impute==0.24.2 (from versions: none)
ERROR: No matching distribution found for sklearn.impute==0.24.2
ERROR: Could not find a version that satisfies the requirement sklearn.impute (from versions: none)
ERROR: No matching distribution found for sklearn.impute

In [ ]:
# This is imputive strategy to fix null value
# from sklearn.impute import Imputer
# from sklearn.preprocessing import Imputer
# imputer = Imputer(strategy="median")
# imputer.fit(housing)
# imputer.statistics